backend:
  name: github
  repo: zachtemkin/still-upright-2
  branch: master
  site_domain: agitated-haibt-5c4e9d.netlify.com

media_folder: src/images

public_folder: /assets

collections:
  - name: posts
    label: Posts
    folder: src/posts
    create: true
    fields:
      - name: contentType
        label: Content Type
        widget: hidden
        default: post
      
      - name: title
        label: Title
      
      - name: date
        label: Date
        widget: datetime

      - name: author
        label: Author
      
      - name: category
        label: Category
        widget: select
        multiple: false
        options: ["pic", "vid", "interactive"]

      - name: heroImage
        label: Hero Image
        widget: "image"

      - name: imageGallery
        label: More Images
        widget: list
        field: { name: image, label: Image, widget: image}

      - name: body
        label: Body
        widget: markdown