backend:
  name: github
  repo: zachtemkin/still-upright-2
  branch: master
  site_domain: agitated-haibt-5c4e9d.netlify.com

media_folder: static/assets

public_folder: /assets

collections:
  - name: posts
    label: Posts
    folder: src/posts
    create: true
    fields:
      - name: path
        label: Path
      
      - name: title
        label: Title
      
      - name: date
        label: Date
        widget: datetime
      
      - name: category
        label: Category
        widget: select
        multiple: false
        options: ["pic", "vid", "interactive"]

      - name: image
        label: Featured Image
        widget: "image"

      
      - name: body
        label: Body
        widget: markdown